name: xianyu-auto-reply
services:
  - name: web
    type: web
    env: container
    dockerImage: registry.cn-shanghai.aliyuncs.com/zhinian-software/xianyu-auto-reply:latest
    region: singapore
    port: 8080
